name: Deploy documentation

on:
  workflow_run:
    workflows: ["Test (Ubuntu)"]
    branches:
      - main
      - ci
    types: [completed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Python dependencies
      run: |
           python -m pip install --upgrade pip
           pip install sphinx sphinx-rtd-theme myst-parser nbsphinx \
                       matplotlib linkify-it-py

    - name: Build documentation
      run: |
           sphinx-build -M html doc/ build/sphinx

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/sphinx/html
